---

cellIdPreamble: "cell-"

cells:
  "leaf1:e1-53:spine1:e1-1":
    dataRef: "oper-state:leaf1:ethernet-1/49"
    datapoint: "lastNotNull"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
