cells:
  "leaf51:e1-53:spine1:e1-1":
    dataRef: "gnmic_srl_if_oper_state_oper_state{source='leaf1', interface_name='e1-53'}"
    fillColor:
      thresholds:
        - {color: "green", level: 1}   # '1' for 'up'
        - {color: "red", level: 0}     # '0' for 'down'
