---
cellIdPreamble: "cell-"
cells:
  leaf1:e1-53:spine1:e1-1:
    dataRef: "oper_state_oper_state:leaf1:ethernet-1/49"
    fillColor:
      thresholds:
        - {color: "green", level: 1}   # '1' for 'up'
        - {color: "red", level: 0}     # '0' for 'down'
